org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23

minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
neo_version=21.4.135
neo_version_range=[21.4.0,)
loader_version_range=[4,)

mod_id=lethifer
mod_name=Lethifer
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.easynull.lethifer
mod_authors=EasyNull
mod_description=...
