# Mod
mod_id=atherys
mod_license=GNU 2.0
mod_version=0.0.2-alpha
mod_group=com.easynull.atherys
mod_authors=easynull
mod_description=Beyond the veil of the familiar world lies an ancient and silent void - Atherys. It is neither dark nor light, but the primordial matter that existed before all else. Few can hear its call, and fewer still can withstand the whispers of its secrets.

# Minecraft
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
neo_version=21.4.138
neo_version_range=[21.4.0,)
loader_version_range=[4,)
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Additions
nullcore_version=1.21.4-0.2.6-neoforge
jei_version=20.0.0.4

# Publish
releaseType=alpha
curseforge_id=...

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true