org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23

minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
neo_version=21.4.135
neo_version_range=[21.4.0,)
loader_version_range=[4,)

mod_id=atherys
mod_name=Atherys
mod_license=GPL 2.0
mod_version=0.0.1a
nullcore_version=1.21.4-0.0.3b
mod_group_id=com.easynull.atherys
mod_authors=easynull
mod_description=...
